runtime: python310
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  CURRENT_URL: "projects/ornate-grin-446817-p3/secrets/CURRENT_URL/versions/latest"
  MONGO_URI: "projects/ornate-grin-446817-p3/secrets/MONGO_URI/versions/latest"
