runtime: python310
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

env_variables:
  CURRENT_URL: "projects/ornate-grin-446817-p3/secrets/CURRENT_URL/versions/latest"
  MONGO_URI: "projects/ornate-grin-446817-p3/secrets/MONGO_URI/versions/latest"
