name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Cambia la rama si es necesario

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ornate-grin-446817-p3
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet
