name: Deploy to Google App Engine

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Auth
      uses: google-github-actions/auth@v2
      with:
        project_id: ornate-grin-446817-p3  # Tu ID de proyecto
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # La clave del servicio de Google Cloud

    - name: Set up cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'


    - name: Modify app.yaml with environment variables
      run: |
        echo "env_variables:" >> app.yaml
        echo "  MONGO_URI: '${{ secrets.MONGO_URI }}'" >> app.yaml
        echo "  CURRENT_URL: '${{ secrets.CURRENT_URL }}'" >> app.yaml

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet
