name: Deploy to Google App Engine

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ornate-grin-446817-p3
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Clean gcloud configuration
      run: |
        gcloud config configurations activate default
        gcloud config unset account
        gcloud config unset project


    - name: Verify gcloud authentication
      run: |
        gcloud auth list
        gcloud config list

    - name: Modify app.yaml with environment variables
      run: |
        echo "env_variables:" >> app.yaml
        echo "  MONGO_URI: '${{ secrets.MONGO_URI }}'" >> app.yaml
        echo "  CURRENT_URL: '${{ secrets.CURRENT_URL }}'" >> app.yaml

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet
